// Auto-generated by /root/kidstown/generate_registry.py from spa-core/data/routing.json
// Maps each (dir, file) pair kt.db can route to onto the JS module that replaced it.
//
// This only lists sections that have actually been converted so far (home,
// library, township, zoo -- see kidstown-spa-work-split.md in the project for
// who owns what). Sections still in progress (cityhall, citypark, museum,
// school, toystore) simply aren't in this table yet; router.js renders a
// clearly-labeled placeholder for anything missing rather than failing the
// whole page, so pages can be spot-checked section by section as teammates
// land their work -- just add more entries here (and an import above) as
// each new section's modules are written.

import * as m0 from "../script/home/about.js";
import * as m1 from "../script/home/helphdr.js";
import * as m2 from "../script/home/helptxt.js";
import * as m3 from "../script/home/ktmap.js";
import * as m4 from "../script/home/mainPgFtr.js";
import * as m5 from "../script/home/mainPgHdr.js";
import * as m6 from "../script/home/mainPgTxt.js";
import * as m7 from "../script/home/Navbar.js";
import * as m8 from "../script/home/participants.js";
import * as m9 from "../script/home/passer.js";
import * as m10 from "../script/library/MidAtlantic.js";
import * as m11 from "../script/library/NewEngland.js";
import * as m12 from "../script/library/NorthCentral.js";
import * as m13 from "../script/library/NorthWest.js";
import * as m14 from "../script/library/SouthCentral.js";
import * as m15 from "../script/library/SouthEast.js";
import * as m16 from "../script/library/SouthWest.js";
import * as m17 from "../script/library/b_ct_tale.js";
import * as m18 from "../script/library/b_dc_fillin_db.js";
import * as m19 from "../script/library/b_fillin_db.js";
import * as m20 from "../script/library/b_ny_fillin_db.js";
import * as m21 from "../script/library/b_or_tale.js";
import * as m22 from "../script/library/b_wi_tale.js";
import * as m23 from "../script/library/ctale.js";
import * as m24 from "../script/library/library.js";
import * as m25 from "../script/library/ortale.js";
import * as m26 from "../script/library/srchpass.js";
import * as m27 from "../script/library/statepage.js";
import * as m28 from "../script/library/witale.js";
import * as m29 from "../script/township/Egypt.js";
import * as m30 from "../script/township/antarc.js";
import * as m31 from "../script/township/china.js";
import * as m32 from "../script/township/finland.js";
import * as m33 from "../script/township/gabon.js";
import * as m34 from "../script/township/jamaica.js";
import * as m35 from "../script/township/laos.js";
import * as m36 from "../script/township/madagas.js";
import * as m37 from "../script/township/maintownship.js";
import * as m38 from "../script/township/mainwonders.js";
import * as m39 from "../script/township/mat_aus.js";
import * as m40 from "../script/township/mat_fran.js";
import * as m41 from "../script/township/mat_jap.js";
import * as m42 from "../script/township/match.js";
import * as m43 from "../script/township/match1.js";
import * as m44 from "../script/township/match1c1.js";
import * as m45 from "../script/township/match1c2.js";
import * as m46 from "../script/township/match1c3.js";
import * as m47 from "../script/township/match2.js";
import * as m48 from "../script/township/match2c1.js";
import * as m49 from "../script/township/match2c2.js";
import * as m50 from "../script/township/match2c3.js";
import * as m51 from "../script/township/match3.js";
import * as m52 from "../script/township/match3c1.js";
import * as m53 from "../script/township/match3c2.js";
import * as m54 from "../script/township/match3c3.js";
import * as m55 from "../script/township/match4.js";
import * as m56 from "../script/township/match4c1.js";
import * as m57 from "../script/township/match4c2.js";
import * as m58 from "../script/township/match4c3.js";
import * as m59 from "../script/township/match5.js";
import * as m60 from "../script/township/match5c1.js";
import * as m61 from "../script/township/match5c2.js";
import * as m62 from "../script/township/match5c3.js";
import * as m63 from "../script/township/match6.js";
import * as m64 from "../script/township/match6c1.js";
import * as m65 from "../script/township/match6c2.js";
import * as m66 from "../script/township/match6c3.js";
import * as m67 from "../script/township/matchbot.js";
import * as m68 from "../script/township/matchhead.js";
import * as m69 from "../script/township/mexico.js";
import * as m70 from "../script/township/pyramid.js";
import * as m71 from "../script/township/saudi.js";
import * as m72 from "../script/township/spain.js";
import * as m73 from "../script/township/tajmahal.js";
import * as m74 from "../script/township/thai.js";
import * as m75 from "../script/township/turkey.js";
import * as m76 from "../script/township/ukraine.js";
import * as m77 from "../script/township/venez.js";
import * as m78 from "../script/township/wall.js";
import * as m79 from "../script/township/wonders.js";
import * as m80 from "../script/township/zeus.js";
import * as m81 from "../script/zoo/africa.js";
import * as m82 from "../script/zoo/australia.js";
import * as m83 from "../script/zoo/ZooBody.js";
import * as m84 from "../script/zoo/d6_af1.js";
import * as m85 from "../script/zoo/d6_af11.js";
import * as m86 from "../script/zoo/d6_af12.js";
import * as m87 from "../script/zoo/d6_af13.js";
import * as m88 from "../script/zoo/d6_ar1.js";
import * as m89 from "../script/zoo/d6_ar11.js";
import * as m90 from "../script/zoo/d6_ar12.js";
import * as m91 from "../script/zoo/d6_ar13.js";
import * as m92 from "../script/zoo/d6_au1.js";
import * as m93 from "../script/zoo/d6_au11.js";
import * as m94 from "../script/zoo/d6_au12.js";
import * as m95 from "../script/zoo/d6_au13.js";
import * as m96 from "../script/zoo/d6_oc1.js";
import * as m97 from "../script/zoo/d6_oc11.js";
import * as m98 from "../script/zoo/d6_oc12.js";
import * as m99 from "../script/zoo/d6_oc13.js";
import * as m100 from "../script/zoo/header.js";
import * as m101 from "../script/zoo/help.js";
import * as m102 from "../script/zoo/ocean.js";
import * as m103 from "../script/zoo/polar.js";
import * as m104 from "../script/zoo/worldmap.js";
import * as m105 from "../script/zoo/zoo.js";
import * as m106 from "../script/zoo/ZooNavbar.js";

export const registry = {
  "homescripts/about.pl": m0,
  "homescripts/helphdr.pl": m1,
  "homescripts/helptxt.pl": m2,
  "homescripts/ktmap.pl": m3,
  "homescripts/mainPgFtr.pl": m4,
  "homescripts/mainPgHdr.pl": m5,
  "homescripts/mainPgTxt.pl": m6,
  "homescripts/navbar.pl": m7,
  "homescripts/participants.pl": m8,
  "homescripts/passer.pl": m9,
  "libraryscripts/MidAtlantic.pl": m10,
  "libraryscripts/NewEngland.pl": m11,
  "libraryscripts/NorthCentral.pl": m12,
  "libraryscripts/NorthWest.pl": m13,
  "libraryscripts/SouthCentral.pl": m14,
  "libraryscripts/SouthEast.pl": m15,
  "libraryscripts/SouthWest.pl": m16,
  "libraryscripts/b_ct_tale.pl": m17,
  "libraryscripts/b_dc_fillin_db.pl": m18,
  "libraryscripts/b_fillin_db.pl": m19,
  "libraryscripts/b_ny_fillin_db.pl": m20,
  "libraryscripts/b_or_tale.pl": m21,
  "libraryscripts/b_wi_tale.pl": m22,
  "libraryscripts/ctale.pl": m23,
  "libraryscripts/library.pl": m24,
  "libraryscripts/ortale.pl": m25,
  "libraryscripts/srchpass.pl": m26,
  "libraryscripts/statepage.pl": m27,
  "libraryscripts/witale.pl": m28,
  "townshipscripts/Egypt.pl": m29,
  "townshipscripts/antarc.pl": m30,
  "townshipscripts/china.pl": m31,
  "townshipscripts/finland.pl": m32,
  "townshipscripts/gabon.pl": m33,
  "townshipscripts/jamaica.pl": m34,
  "townshipscripts/laos.pl": m35,
  "townshipscripts/madagas.pl": m36,
  "townshipscripts/maintownship.pl": m37,
  "townshipscripts/mainwonders.pl": m38,
  "townshipscripts/mat_aus.pl": m39,
  "townshipscripts/mat_fran.pl": m40,
  "townshipscripts/mat_jap.pl": m41,
  "townshipscripts/match.pl": m42,
  "townshipscripts/match1.pl": m43,
  "townshipscripts/match1c1.pl": m44,
  "townshipscripts/match1c2.pl": m45,
  "townshipscripts/match1c3.pl": m46,
  "townshipscripts/match2.pl": m47,
  "townshipscripts/match2c1.pl": m48,
  "townshipscripts/match2c2.pl": m49,
  "townshipscripts/match2c3.pl": m50,
  "townshipscripts/match3.pl": m51,
  "townshipscripts/match3c1.pl": m52,
  "townshipscripts/match3c2.pl": m53,
  "townshipscripts/match3c3.pl": m54,
  "townshipscripts/match4.pl": m55,
  "townshipscripts/match4c1.pl": m56,
  "townshipscripts/match4c2.pl": m57,
  "townshipscripts/match4c3.pl": m58,
  "townshipscripts/match5.pl": m59,
  "townshipscripts/match5c1.pl": m60,
  "townshipscripts/match5c2.pl": m61,
  "townshipscripts/match5c3.pl": m62,
  "townshipscripts/match6.pl": m63,
  "townshipscripts/match6c1.pl": m64,
  "townshipscripts/match6c2.pl": m65,
  "townshipscripts/match6c3.pl": m66,
  "townshipscripts/matchbot.pl": m67,
  "townshipscripts/matchhead.pl": m68,
  "townshipscripts/mexico.pl": m69,
  "townshipscripts/pyramid.pl": m70,
  "townshipscripts/saudi.pl": m71,
  "townshipscripts/spain.pl": m72,
  "townshipscripts/tajmahal.pl": m73,
  "townshipscripts/thai.pl": m74,
  "townshipscripts/turkey.pl": m75,
  "townshipscripts/ukraine.pl": m76,
  "townshipscripts/venez.pl": m77,
  "townshipscripts/wall.pl": m78,
  "townshipscripts/wonders.pl": m79,
  "townshipscripts/zeus.pl": m80,
  "zooscripts/africa.pl": m81,
  "zooscripts/australia.pl": m82,
  "zooscripts/body.pl": m83,
  "zooscripts/d6_af1.pl": m84,
  "zooscripts/d6_af11.pl": m85,
  "zooscripts/d6_af12.pl": m86,
  "zooscripts/d6_af13.pl": m87,
  "zooscripts/d6_ar1.pl": m88,
  "zooscripts/d6_ar11.pl": m89,
  "zooscripts/d6_ar12.pl": m90,
  "zooscripts/d6_ar13.pl": m91,
  "zooscripts/d6_au1.pl": m92,
  "zooscripts/d6_au11.pl": m93,
  "zooscripts/d6_au12.pl": m94,
  "zooscripts/d6_au13.pl": m95,
  "zooscripts/d6_oc1.pl": m96,
  "zooscripts/d6_oc11.pl": m97,
  "zooscripts/d6_oc12.pl": m98,
  "zooscripts/d6_oc13.pl": m99,
  "zooscripts/header.pl": m100,
  "zooscripts/help.pl": m101,
  "zooscripts/ocean.pl": m102,
  "zooscripts/polar.pl": m103,
  "zooscripts/worldmap.pl": m104,
  "zooscripts/zoo.pl": m105,
  "zooscripts/zoonavbar.pl": m106,
};

// The confirmed kt.db line-489 typo: KEY=6020's navbar chain entry uses the
// misspelled directory "homescritps" (missing the "p"->"ps" swap) instead of
// "homescripts". kt.ini has no matching alias, so in the ORIGINAL engine this
// made kt.cgi try to open the literal relative path "homescritps/navbar.pl",
// which failed and made the whole CGI process die() mid-page (killing that
// request -- no navbar, no closing </HTML>, nothing after it in the chain).
// Flagged in the team checklist for a decision; router.js intentionally does
// NOT reproduce a hard crash for it (or for any other unresolvable entry --
// including sections teammates haven't finished yet) and instead renders a
// visible placeholder comment, which is far more useful for spot-checking a
// site under construction than silently matching 1998's failure mode.
export const KNOWN_BROKEN_DIR = "homescritps";

